import { Trade } from './interfaces/trade';

export class InMemoryDataService {
  createDb() {
    const trades: Trade[] = [
      {
        id: 1,
        name: 'Bob the king',
        tradeType: "Trade",
        transactionDate: "10-07-2018",
        buyAmount: 20,
        buyCurrency: "BTC",
        sellAmount: 2000,
        sellCurrency: "USD",
        tradingFeeAmount: 20,
        tradingFeeCurrency: "USD",
        other: "Lorem ipsum dolor sit amet, ex dolorem officiis convenire usu."
      },
      {
        id: 2,
        name: 'Nicholas DuBuque',
        tradeType: "Trade",
        transactionDate: "10-09-2018",
        buyAmount: 3,
        buyCurrency: "BTC",
        sellAmount: 400,
        sellCurrency: "USD",
        tradingFeeAmount: 10,
        tradingFeeCurrency: "USD",
        other: "Ex dolorem officiis convenire usu."
      },
      {
        id: 3,
        name: 'Niche Name',
        tradeType: "Trade",
        transactionDate: "12-07-2018",
        buyAmount: 50,
        buyCurrency: "ETH",
        sellAmount: 280,
        sellCurrency: "USD",
        tradingFeeAmount: 8,
        tradingFeeCurrency: "USD",
        other: "Officiis convenire usu."
      },
      {
        id: 5,
        name: 'Brock Lesner',
        tradeType: "Trade",
        transactionDate: "7-07-2018",
        buyAmount: 2,
        buyCurrency: "BTC",
        sellAmount: 800,
        sellCurrency: "USD",
        tradingFeeAmount: 2,
        tradingFeeCurrency: "USD",
        other: "Ipsum dolor sit amet, convenire usu."
      },
      {
        id: 6,
        name: 'Nicholas DuBuque',
        tradeType: "Trade",
        transactionDate: "9-07-2018",
        buyAmount: 15,
        buyCurrency: "ETH",
        sellAmount: 20,
        sellCurrency: "USD",
        tradingFeeAmount: 20,
        tradingFeeCurrency: "USD",
        other: "Lorem ipsum dolor sit amet, ex dolorem officiis convenire usu."
      },
      {
        id: 1,
        name: 'Bob the king',
        tradeType: "Trade",
        transactionDate: "10-07-2018",
        buyAmount: 20,
        buyCurrency: "BTC",
        sellAmount: 2000,
        sellCurrency: "USD",
        tradingFeeAmount: 20,
        tradingFeeCurrency: "USD",
        other: "Lorem ipsum dolor sit amet, ex dolorem officiis convenire usu."
      },
      {
        id: 2,
        name: 'Nicholas DuBuque',
        tradeType: "Trade",
        transactionDate: "10-09-2018",
        buyAmount: 3,
        buyCurrency: "BTC",
        sellAmount: 400,
        sellCurrency: "USD",
        tradingFeeAmount: 10,
        tradingFeeCurrency: "USD",
        other: "Ex dolorem officiis convenire usu."
      },
      {
        id: 3,
        name: 'Niche Name',
        tradeType: "Trade",
        transactionDate: "12-07-2018",
        buyAmount: 50,
        buyCurrency: "ETH",
        sellAmount: 280,
        sellCurrency: "USD",
        tradingFeeAmount: 8,
        tradingFeeCurrency: "USD",
        other: "Officiis convenire usu."
      },
      {
        id: 5,
        name: 'Brock Lesner',
        tradeType: "Trade",
        transactionDate: "7-07-2018",
        buyAmount: 2,
        buyCurrency: "BTC",
        sellAmount: 800,
        sellCurrency: "USD",
        tradingFeeAmount: 2,
        tradingFeeCurrency: "USD",
        other: "Ipsum dolor sit amet, convenire usu."
      },
      {
        id: 6,
        name: 'Nicholas DuBuque',
        tradeType: "Trade",
        transactionDate: "9-07-2018",
        buyAmount: 15,
        buyCurrency: "ETH",
        sellAmount: 20,
        sellCurrency: "USD",
        tradingFeeAmount: 20,
        tradingFeeCurrency: "USD",
        other: "Lorem ipsum dolor sit amet, ex dolorem officiis convenire usu."
      },
      {
        id: 1,
        name: 'Bob the king',
        tradeType: "Trade",
        transactionDate: "10-07-2018",
        buyAmount: 20,
        buyCurrency: "BTC",
        sellAmount: 2000,
        sellCurrency: "USD",
        tradingFeeAmount: 20,
        tradingFeeCurrency: "USD",
        other: "Lorem ipsum dolor sit amet, ex dolorem officiis convenire usu."
      },
      {
        id: 2,
        name: 'Nicholas DuBuque',
        tradeType: "Trade",
        transactionDate: "10-09-2018",
        buyAmount: 3,
        buyCurrency: "BTC",
        sellAmount: 400,
        sellCurrency: "USD",
        tradingFeeAmount: 10,
        tradingFeeCurrency: "USD",
        other: "Ex dolorem officiis convenire usu."
      },
      {
        id: 3,
        name: 'Niche Name',
        tradeType: "Trade",
        transactionDate: "12-07-2018",
        buyAmount: 50,
        buyCurrency: "ETH",
        sellAmount: 280,
        sellCurrency: "USD",
        tradingFeeAmount: 8,
        tradingFeeCurrency: "USD",
        other: "Officiis convenire usu."
      },
      {
        id: 5,
        name: 'Brock Lesner',
        tradeType: "Trade",
        transactionDate: "7-07-2018",
        buyAmount: 2,
        buyCurrency: "BTC",
        sellAmount: 800,
        sellCurrency: "USD",
        tradingFeeAmount: 2,
        tradingFeeCurrency: "USD",
        other: "Ipsum dolor sit amet, convenire usu."
      },
      {
        id: 6,
        name: 'Nicholas DuBuque',
        tradeType: "Trade",
        transactionDate: "9-07-2018",
        buyAmount: 15,
        buyCurrency: "ETH",
        sellAmount: 20,
        sellCurrency: "USD",
        tradingFeeAmount: 20,
        tradingFeeCurrency: "USD",
        other: "Lorem ipsum dolor sit amet, ex dolorem officiis convenire usu."
      },
      
    ];
    return { trades };
  }
}
